#ifndef INSTRUCTION_H
#define INSTRUCTION_H

#include <stdint.h>

typedef enum {
    INSTRUCTION_0NNN,
    INSTRUCTION_00E0,
    INSTRUCTION_1NNN,
    INSTRUCTION_00EE,
    INSTRUCTION_2NNN,
    INSTRUCTION_3XNN,
    INSTRUCTION_4XNN,
    INSTRUCTION_5XYN,
    INSTRUCTION_9XY0,
    INSTRUCTION_6XNN,
    INSTRUCTION_7XNN,
    INSTRUCTION_NULL,
    INSTRUCTION_MAX
} INSTRUCTION;
    
INSTRUCTION instruction_get(uint16_t instruction);

#endif // INSTRUCTION_H
